import Head from 'next/head'
import Image from 'next/image'
import { GetServerSideProps } from 'next'
import { countDays, latestIncident, hashids } from '../lib/lib'
import { prisma } from '../lib/db'
import styles from '../styles/Home.module.css'
import PageCard from '../components/PageCard'
import Header from '../components/Header'

export const getServerSideProps: GetServerSideProps = async (context) => {


  const pages = await prisma.page.findMany({
    include: { 
      incidents: true,
    },
  })

  //console.log(pages)
  const uiPages = await Promise.all(
    pages.map(async page => {
    const latest = latestIncident(page.incidents)
    let lastEditedBy = null
    if (latest !== null && latest.userId !== null) {
      const user = await prisma.user.findUnique({
        where: {
          id: latest.userId
        }
      })
      
      lastEditedBy = {
        name: user.name,
        image: user.image,
      }
    }

    return {
      count: countDays(page.incidents),
      id: hashids.encode(page.id),
      title: page.title,
      lastEditedBy: lastEditedBy,
    }
  }))

  return { props: { pages: uiPages } }
}

interface HomeProps {
  pages: { 
    count: number, 
    id: string, 
    title: string, 
    lastEditedBy?: { name: string, image: string },
  }[],
}

export default function Home(props: HomeProps) {

  const pages = props.pages.map(page => (
    <PageCard key={page.id} page={page}></PageCard>
  ))

  return (
    <div>
      <Head>
        <title>Daysie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="min-h-screen flex place-content-center p-4">
        <div className="flex flex-col gap-3 h-fit">
          {pages}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
